### PR TITLE
add refcounted global config

### PR DESCRIPTION
**Pull request by bengreenier**
Provides global configuration support at top level access locations using https://github.com/bengreenier/cppfactory as a pattern provider.

replaces static configuration parsing support for gobally refcounted objects representing parsed configuration that are lazy initialized. This means we only read from disk once, and can mock config in memory for testing purposes.

- [x] write tests
- [x] swap any config double-read calls in the lower depths of our libraries for `GlobalObject` access

### CODE REVIEW

**Comment by bengreenier** [comment]
currently tagged invalid, as it's missing components required before we're ready to merge this

**Comment by bengreenier** [comment]
see #114

**Comment by bengreenier** [comment]
@phongcao @anderm can someone review this when they have a moment? we should be good to ship this! :shipit: 🚀

**Comment by bengreenier** [comment]
@anderm good catch! cleaned that up, hoping i can get your final signoff and we can :shipit: 🚀

**Comment by anderm** [comment]
@bengreenier GTG! Merging now

**Pull request merged**
