### PR TITLE
improved server security

### PR DESCRIPTION
**Pull request by bengreenier**
This adds support for serverside authentication using the oauth2 `client_credentials` grant type and aad (note: only aad v1 authentication flows are currently supported) to securely communicate with a signaling server

### CODE REVIEW

**Comment by bengreenier** [comment]
can we plz squash and merge this - i don't want to see my "wip" style commits in our history forever 😅

**Comment by bengreenier** [comment]
the `MultithreadedTestRunner` and the `SpinningCubeTestRunner` projects consume dependencies differently and it get's me every time. i'm going to fix them.

**Comment by anastasiia-zolochevska** [comment]
Could you please also update webrtcConfig.json with auth config values (don't check in secret), everything else is publiuc

**Comment by bengreenier** [comment]
changed the name since as we agreed we're going to land temporary turn credentials here as well.

**Comment by bengreenier** [comment]
closing in favor of https://github.com/CatalystCode/3dtoolkit/pull/63

**Pull request closed without merging**
